version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intranet

  discord-game-server-monitor:
    container_name: discord-game-server-monitor
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-game-server-monitor:local
    command: /bin/sh -c "gunicorn --bind 0.0.0.0:8000 --workers=2 --worker-class=gthread app:app --timeout 90 & python -u main.py"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_password@postgres:5432/postgres_db
      - POSTGRES_SSL_MODE=disable
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - intranet

networks:
  intranet:

volumes:
  postgres_data:
